version: '3.7'

services:
  main:
    container_name: jet
    build:
      context: .
      dockerfile: Dockerfile
    image: duretrip/jet:latest
    restart: always
    ports:
      - 8007:8007
    env_file:
      - .env.dev